### ISSUE TITLE
Lazy import from init

### ISSUE THREAD

**Issue by burakyilmaz321** [invent-analytics/metaframe#3]
This is a single class library. Users will most likely to use the ``MetaFrame`` class only. So it would be better if we can do that like ``from metaframe import MetaFrame``, instead of current ``from metaframe.metaframe import MetaFrame``.

One way to do this is to define ``MetaFrame`` within ``__init__.py``, or just importing it there. But sometimes this causes some unwanted overheads if importing ``metaframe.MetaFrame`` is costly.

And, if we put package metadata like ``__version__``, there might be build time dependency problems. ``metaframe.__init__.py`` will be imported at the build time. There should be an error since ``pyspark`` is not a build time dependency. (I did't tested this. Not 100% sure.)

I think we can try lazy module imports to handle this. It's kind of hacky but [I used it somewhere else](https://github.com/burakyilmaz321/tefas-crawler/blob/main/tefas/__init__.py), and saw some similer approaches.

It should be something like

```python
# __init__.py

def __getattr__(name):
    if name == "Crawler":
        from metaframe.metaframe import MetaFrame
        return MetaFrame
```

But.. this works only for python>3.7 (see [PEP-562](https://www.python.org/dev/peps/pep-0562/))

**Comment by sagmansercan** [comment]
Hi @burakyilmaz321 

Thanks for the detailed explanation. I've searched on PEP-562, navigated to related [PR](https://github.com/ilevkivskyi/cpython/pull/3) but it seems that it was closed. I couldn't be sure if this feature is supported in python 3.7, so I just decided to try your proposed implementation via python 3.7.0.

Here is `__init__.py`;

```py
__all__ = ["MetaFrame"]

def __getattr__(name):
    if name == "MetaFrame":
        from metaframe.metaframe import MetaFrame
        return MetaFrame
```
My test script;
```py
from pyspark.sql import SparkSession
from metaframe import MetaFrame


spark = (
    SparkSession
    .builder
    .master("local")
    .appName("metaframe-testing")
    .getOrCreate()
)


spark_df = spark.range(5)
df = MetaFrame(spark_df, metadata={"columns": ["id"]})
print(df)
print(df.show())
```

and the test output;

```py
DataFrame[id: bigint] metadata: {'columns': ['id']}
+---+
| id|
+---+
|  0|
|  1|
|  2|
|  3|
|  4|
+---+
```

However, you mentioned that it is only working with `>3.7`. This project requires `>=3.7`, and the implementation seems working with python 3.7.0 without any problem. Is it a typo or is there anything that I missed here?

**Comment by burakyilmaz321** [comment]
Yes, apparently it is a typo. It should be "python>=3.7".

**Comment by sagmansercan** [comment]
Alright then, what is the concern here? This project already requires python>=3.7. Does this mean that python 3.6 should also be supported because spark supports >=3.6?

**Comment by burakyilmaz321** [comment]
I guess I was just asking "should we do this?". So, if everyone agree, we can do that. I don't think we should support python 3.6 just because spark does. Requiring python>=3.7 is fine for me.
